The problem with adding data to db: any item containing more then 1 symbol in the list tab_name (line 5) (for example, tab_name = ['A', 'B', 'Cc']) causes error like below:
Traceback (most recent call last):
  File "C:/Users/Богдан/PycharmProjects/DZ/train.py", line 6, in <module>
    cur.executemany("INSERT INTO tab (name) VALUES (?)", tab_name)
sqlite3.ProgrammingError: Incorrect number of bindings supplied. The current statement uses 1, and there are 2 supplied.

Process finished with exit code 1